In [ ]:
#Naive Base-1 (SMS Spam )
from google.colab import files #to import the files to local machine
files.upload()      #for upload the files

Saving spam.csv to spam.csv

{'spam.csv': b'v1,v2,,,\r\nham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,\r\nham,Ok lar... Joking wif u oni...,,,\r\nspam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C\'s apply 08452810075over18\'s,,,\r\nham,U dun say so early hor... U c already then say...,,,\r\nham,"Nah I don\'t think he goes to usf, he lives around here though",,,\r\nspam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, \xe5\xa31.50 to rcv",,,\r\nham,Even my brother is not like to speak with me. They treat me like aids patent.,,,\r\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,\r\nspam,WINNER!! As a valued network customer you have been selected to receivea \xe5\xa3900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,\r\nspam,Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030,,,\r\nham,"I\'m gonna be home soon and i don\'t want to talk about this stuff anymore tonight, k? I\'ve cried enough today.",,,\r\nspam,"SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info",,,\r\nspam,"URGENT! You have won a 1 week FREE membership in our \xe5\xa3100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18",,,\r\nham,I\'ve been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.,,,\r\nham,I HAVE A DATE ON SUNDAY WITH WILL!!,,,\r\nspam,"XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL",,,\r\nham,Oh k...i\'m watching here:),,,\r\nham,Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.,,,\r\nham,Fine if that\xe5\xd5s the way u feel. That\xe5\xd5s the way its gota b,,,\r\nspam,"England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/\xcc\xbc1.20 POBOXox36504W45WQ 16+",,,\r\nham,Is that seriously how you spell his name?,,,\r\nham,I\x89\xdb\xf7m going to try for 2 months ha ha only joking,,,\r\nham,So \xcc_ pay first lar... Then when is da stock comin...,,,\r\nham,Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?,,,\r\nham,Ffffffffff. Alright no way I can meet up with you sooner?,,,\r\nham,Just forced myself to eat a slice. I\'m really not hungry tho. This sucks. Mark is getting worried. He knows I\'m sick when I turn down pizza. Lol,,,\r\nham,Lol your always so convincing.,,,\r\nham,Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom\'s left over dinner ? Do you feel my Love ?,,,\r\nham,"I\'m back &amp; we\'re packing the car now, I\'ll let you know if there\'s room",,,\r\nham,Ahhh. Work. I vaguely remember that! What does it feel like? Lol,,,\r\nham,"Wait that\'s still not all that clear, were you not sure about me being sarcastic or that that\'s why x doesn\'t want to live with us",,,\r\nham,Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won\'t go there! Not doing too badly cheers. You? ,,,\r\nham,K tell me anything about you.,,,\r\nham,For fear of fainting with the of all that housework you just did? Quick have a cuppa,,,\r\nspam,Thanks for your subscription to Ringtone UK your mobile will be charged \xe5\xa35/month Please confirm by replying YES or NO. If you reply NO you will not be charged,,,\r\nham,Yup... Ok i go home look at the timings then i msg \xcc_ again... Xuhui going to learn on 2nd may too but her lesson is at 8am,,,\r\nham,"Oops, I\'ll let you know when my roommate\'s done",,,\r\nham,I see the letter B on my car,,,\r\nham,Anything lor... U decide...,,,\r\nham,Hello! How\'s you and how did saturday go? I was just texting to see if you\'d decided to do anything tomo. Not that i\'m trying to invite myself or anything!,,,\r\nham,Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola,,,\r\nham,"Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy",,,\r\nspam,07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow,,,\r\nham,WHO ARE YOU SEEING?,,,\r\nham,Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...,,,\r\nham,No calls..messages..missed calls,,,\r\nham,Didn\'t you get hep b immunisation in nigeria.,,,\r\nham,"Fair enough, anything going on?",,,\r\nham,"Yeah hopefully, if tyler can\'t do it I could maybe ask around a bit",,,\r\nham,U don\'t know how stubborn I am. I didn\'t even want to go to the hospital. I kept telling Mark I\'m not a weak sucker. Hospitals are for weak suckers.,,,\r\nham,What you thinked about me. First time you saw me in class.,,,\r\nham,"A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;",,,\r\nham,K fyi x has a ride early tomorrow morning but he\'s crashing at our place tonight,,,\r\nham,"Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about \\the cave\\"". I\'m sorry I didn\'t and don\'t have more to give. I\'m sorry i offered. I\'m sorry your room was so embarassing.""",,,\r\nspam,SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV,,,\r\nham,Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;,,,\r\nspam,"Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! ",,,\r\nham,"Sorry, I\'ll call later in meeting.",,,\r\nham,Tell where you reached,,,\r\nham,Yes..gauti and sehwag out of odi series.,,,\r\nham,Your gonna have to pick up a $1 burger for yourself on your way home. I can\'t even move. Pain is killing me.,,,\r\nham,Ha ha ha good joke. Girls are situation seekers.,,,\r\nham,Its a part of checking IQ,,,\r\nham,"Sorry my roommates took forever, it ok if I come by now?",,,\r\nham,Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.,,,\r\nspam,"As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a \xe5\xa31500 Bonus Prize, call 09066364589",,,\r\nham,"Today is \\song dedicated day..\\"" Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me...""",,,\r\nspam,"Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or \xe5\xa31000. To claim txt DIS to 87121 18+6*\xe5\xa31.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ",,,\r\nspam,"Did you hear about the new \\Divorce Barbie\\""? It comes with all of Ken\'s stuff!""",,,\r\nham,I plane to give on this month end.,,,\r\nham,Wah lucky man... Then can save money... Hee...,,,\r\nham,Finished class where are you.,,,\r\nham,HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX,,,\r\nham,K..k:)where are you?how did you performed?,,,\r\nham,U can call me now...,,,\r\nham,I am waiting machan. Call me once you free.,,,\r\nham,Thats cool. i am a gentleman and will treat you with dignity and respect.,,,\r\nham,I like you peoples very much:) but am very shy pa.,,,\r\nham,Does not operate after  &lt;#&gt;  or what,,,\r\nham,Its not the same here. Still looking for a job. How much do Ta\'s earn there.,,,\r\nham,"Sorry, I\'ll call later",,,\r\nham,K. Did you call me just now ah? ,,,\r\nham,Ok i am on the way to home hi hi,,,\r\nham,You will be in the place of that man,,,\r\nham,Yup next stop.,,,\r\nham,"I call you later, don\'t have network. If urgnt, sms me.",,,\r\nham,For real when u getting on yo? I only need 2 more tickets and one more jacket and I\'m done. I already used all my multis.,,,\r\nham,Yes I started to send requests to make it but pain came back so I\'m back in bed. Double coins at the factory too. I gotta cash in all my nitros.,,,\r\nham,I\'m really not up to it still tonight babe,,,\r\nham,"Ela kano.,il download, come wen ur free..",,,\r\nham,Yeah do! Don\x89\xdb\xf7t stand to close tho- you\x89\xdb\xf7ll catch something!,,,\r\nham,Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven\'t done any of y stuff42moro and that includes all my time sheets and that. Sorry. ,,,\r\nham,Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!,,,\r\nspam,Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed \xe5\xa31000 cash or \xe5\xa35000 prize!,,,\r\nham,Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?,,,\r\nspam,"Your free ringtone is waiting to be collected. Simply text the password \\MIX\\"" to 85069 to verify. Get Usher and Britney. FML", PO Box 5249," MK17 92H. 450Ppw 16""",\r\nham,Watching telugu movie..wat abt u?,,,\r\nham,i see. When we finish we have loads of loans to pay,,,\r\nham,"Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?\\""\rham""",,,\r\nham,Please don\'t text me anymore. I have nothing else to say.,,,\r\nham,Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx,,,\r\nham,I\'m still looking for a car to buy. And have not gone 4the driving test yet.,,,\r\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,\r\nham,"wow. You\'re right! I didn\'t mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston.",,,\r\nham,Umma my life and vava umma love you lot dear,,,\r\nham,Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.,,,\r\nham,"Aight, I\'ll hit you up when I get some cash",,,\r\nham,How would my ip address test that considering my computer isn\'t a minecraft server,,,\r\nham,I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...,,,\r\nham,Dont worry. I guess he\'s busy.,,,\r\nham,What is the plural of the noun research?,,,\r\nham,Going for dinner.msg you after.,,,\r\nham,I\'m ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.,,,\r\nspam,GENT! We are trying to contact you. Last weekends draw shows that you won a \xe5\xa31000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm,,,\r\nham,"Wa, ur openin sentence very formal... Anyway, i\'m fine too, juz tt i\'m eatin too much n puttin on weight...Haha... So anythin special happened?",,,\r\nham,"As I entered my cabin my PA said, \'\' Happy B\'day Boss !!\'\'. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.",,,\r\nspam,You are a winner U have been specially selected 2 receive \xe5\xa31000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ,,,\r\nham,Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed! ,,,\r\nham,Hmm...my uncle just informed me that he\'s paying the school directly. So pls buy food.,,,\r\nspam,PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires,,,\r\nspam,"URGENT! Your Mobile No. was awarded \xe5\xa32000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM",,,\r\nham,here is my new address -apples&pairs&all that malarky,,,\r\nspam,Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app,,,\r\nham,I am going to sao mu today. Will be done only at 12 ,,,\r\nham,\xcc\xcf predict wat time \xcc_\'ll finish buying?,,,\r\nham,"Good stuff, will do.",,,\r\nham,"Just so that you know,yetunde hasn\'t sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn\'t have imposed anything on you in the first place so for that, i apologise.",,,\r\nham,Are you there in room.,,,\r\nham,HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx,,,\r\nham,K..k:)how much does it cost?,,,\r\nham,I\'m home.,,,\r\nham,"Dear, will call Tmorrow.pls accomodate.",,,\r\nham,First answer my question.,,,\r\nspam,Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. \xe5\xa31.50 SP:Tyrone,,,\r\nspam,Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK\'s largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p,,,\r\nham,I only haf msn. It\'s yijue@hotmail.com,,,\r\nham,He is there. You call and meet him,,,\r\nham,No no. I will check all rooms befor activities,,,\r\nspam,You\'ll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again,,,\r\nham,Got c... I lazy to type... I forgot \xcc_ in lect... I saw a pouch but like not v nice...,,,\r\nham,"K, text me when you\'re on the way",,,\r\nham,"Sir, Waiting for your mail.",,,\r\nham,"A swt thought: \\Nver get tired of doing little things 4 lovable persons..\\"" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8""",,,\r\nham,I know you are. Can you pls open the back?,,,\r\nham,Yes see ya not on the dot,,,\r\nham,Whats the staff name who is taking class for us?,,,\r\nspam,"FreeMsg Why haven\'t you replied to my text? I\'m Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end",,,\r\nham,Ummma.will call after check in.our life will begin from qatar so pls pray very hard.,,,\r\nham,K..i deleted my contact that why?,,,\r\nham,Sindu got job in birla soft ..,,,\r\nham,The wine is flowing and i\'m i have nevering..,,,\r\nham,Yup i thk cine is better cos no need 2 go down 2 plaza mah.,,,\r\nham,Ok... Ur typical reply...,,,\r\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,\r\nham,"You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.",,,\r\nham,Aaooooright are you at work?,,,\r\nham,I\'m leaving my house now...,,,\r\nham,"Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?",,,\r\nspam,Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery,,,\r\nspam,You are a winner U have been specially selected 2 receive \xe5\xa31000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810,,,\r\nham,Keep yourself safe for me because I need you and I miss you already and I envy everyone that see\'s you in real life,,,\r\nham,New car and house for my parents.:)i have only new job in hand:),,,\r\nham,I\'m so in love with you. I\'m excited each day i spend with you. You make me so happy.,,,\r\nspam,-PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468,,,\r\nspam,"BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu",,,\r\nham,I place all ur points on e cultures module already.,,,\r\nspam,URGENT! We are trying to contact you. Last weekends draw shows that you have won a \xe5\xa3900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only,,,\r\nham,"Hi frnd, which is best way to avoid missunderstding wit our beloved one\'s?",,,\r\nham,Great escape. I fancy the bridge but needs her lager. See you tomo ,,,\r\nham,Yes :)it completely in out of form:)clark also utter waste.,,,\r\nham,"Sir, I need AXIS BANK account no and bank address.",,,\r\nham,"Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao... ",,,\r\nham,What time you coming down later? ,,,\r\nham,"Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m... ",,,\r\nham,"Well, i\'m gonna finish my bath now. Have a good...fine night.",,,\r\nham,Let me know when you\'ve got the money so carlos can make the call,,,\r\nham,U still going to the mall?,,,\r\nham,"Turns out my friends are staying for the whole show and won\'t be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth",,,\r\nham,Text her. If she doesnt reply let me know so i can have her log in,,,\r\nham,Hi! You just spoke to MANEESHA V. We\'d like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.,,,\r\nham,You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend,,,\r\nham,Lol no. U can trust me.,,,\r\nham,ok. I am a gentleman and will treat you with dignity and respect.,,,\r\nham,"He will, you guys close?",,,\r\nham,Going on nothing great.bye,,,\r\nham,Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where\'s my boytoy now ? Does he miss me ?,,,\r\nham,"Haha awesome, be there in a minute",,,\r\nspam,Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed \xe5\xa31000 cash or \xe5\xa35000 prize!,,,\r\nham,Have you got Xmas radio times. If not i will get it now,,,\r\nham,I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...,,,\r\nspam,Are you unique enough? Find out from 30th August. www.areyouunique.co.uk,,,\r\nham,I\'m sorry. I\'ve joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|,,,\r\nham,Hi :)finally i completed the course:),,,\r\nham,It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.,,,\r\nham,How are you doing? Hope you\'ve settled in for the new school year. Just wishin you a gr8 day,,,\r\nham,Gud mrng dear hav a nice day,,,\r\nham,Did u got that persons story,,,\r\nham,is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt? ,,,\r\nham,Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bl

In [ ]:
import numpy as np #for work with numeric data in dataset
import pandas as pd #for manupulate and analysis the dataset

In [ ]:
df=pd.read_csv('spam.csv', encoding='latin1') # TO read the csv file
df.head()  #to show the 1st 5 row

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
df.isnull().sum()     # to check how many NaN exist in a spacific row

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [ ]:
# drop the NaN column
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)     #drop the NaN column
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Convert text to features using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(df['v2'])

In [ ]:
print(cv.vocabulary_)   # Frequency of the existing word (word repeating time )

{'go': 3550, 'until': 8030, 'jurong': 4350, 'point': 5920, 'crazy': 2327, 'available': 1303, 'only': 5537, 'in': 4087, 'bugis': 1751, 'great': 3634, 'world': 8489, 'la': 4476, 'buffet': 1749, 'cine': 2048, 'there': 7645, 'got': 3594, 'amore': 1069, 'wat': 8267, 'ok': 5504, 'lar': 4512, 'joking': 4318, 'wif': 8392, 'oni': 5533, 'free': 3358, 'entry': 2949, 'wkly': 8447, 'comp': 2165, 'to': 7756, 'win': 8405, 'fa': 3087, 'cup': 2386, 'final': 3207, 'tkts': 7743, '21st': 411, 'may': 4930, '2005': 402, 'text': 7595, '87121': 784, 'receive': 6297, 'question': 6190, 'std': 7230, 'txt': 7933, 'rate': 6242, 'apply': 1156, '08452810075over18': 77, 'dun': 2802, 'say': 6633, 'so': 7024, 'early': 2823, 'hor': 3927, 'already': 1042, 'then': 7640, 'nah': 5238, 'don': 2712, 'think': 7660, 'he': 3781, 'goes': 3558, 'usf': 8075, 'lives': 4665, 'around': 1207, 'here': 3831, 'though': 7680, 'freemsg': 3365, 'hey': 3841, 'darling': 2443, 'it': 4218, 'been': 1460, 'week': 8313, 'now': 5420, 'and': 1084, 'no': 5367, 'word': 8480, 'back': 1351, 'like': 4615, 'some': 7039, 'fun': 3419, 'you': 8609, 'up': 8032, 'for': 3308, 'still': 7253, 'tb': 7529, 'xxx': 8555, 'chgs': 2002, 'send': 6723, '50': 607, 'rcv': 6255, 'even': 2998, 'my': 5223, 'brother': 1722, 'is': 4206, 'not': 5405, 'speak': 7112, 'with': 8433, 'me': 4939, 'they': 7653, 'treat': 7863, 'aids': 992, 'patent': 5722, 'as': 1224, 'per': 5764, 'your': 8615, 'request': 6406, 'melle': 4969, 'oru': 5593, 'minnaminunginte': 5036, 'nurungu': 5440, 'vettam': 8131, 'has': 3757, 'set': 6750, 'callertune': 1823, 'all': 1029, 'callers': 1822, 'press': 6041, 'copy': 2266, 'friends': 3381, 'winner': 8416, 'valued': 8100, 'network': 5317, 'customer': 2399, 'have': 3770, 'selected': 6709, 'receivea': 6298, '900': 816, 'prize': 6073, 'reward': 6461, 'claim': 2054, 'call': 1813, '09061701461': 224, 'code': 2120, 'kl341': 4439, 'valid': 8096, '12': 322, 'hours': 3947, 'had': 3699, 'mobile': 5089, '11': 312, 'months': 5129, 'or': 5570, 'more': 5133, 'entitled': 2946, 'update': 8037, 'the': 7627, 'latest': 4526, 'colour': 2141, 'mobiles': 5090, 'camera': 1835, 'co': 2109, 'on': 5525, '08002986030': 61, 'gonna': 3574, 'be': 1438, 'home': 3901, 'soon': 7066, 'want': 8245, 'talk': 7496, 'about': 859, 'this': 7669, 'stuff': 7320, 'anymore': 1123, 'tonight': 7792, 've': 8115, 'cried': 2344, 'enough': 2936, 'today': 7763, 'six': 6928, 'chances': 1943, 'cash': 1889, 'from': 3397, '100': 298, '20': 397, '000': 1, 'pounds': 5982, 'csh11': 2363, '87575': 789, 'cost': 2278, '150p': 351, 'day': 2458, '6days': 680, '16': 363, 'tsandcs': 7898, 'reply': 6399, 'hl': 3873, 'info': 4122, 'urgent': 8055, 'won': 8464, 'membership': 4975, 'our': 5606, 'jackpot': 4247, '81010': 737, 'www': 8537, 'dbuk': 2463, 'net': 5311, 'lccltd': 4543, 'pobox': 5899, '4403ldnw1a7rw18': 559, 'searching': 6678, 'right': 6473, 'words': 8481, 'thank': 7612, 'breather': 1691, 'promise': 6105, 'wont': 8471, 'take': 7488, 'help': 3817, 'granted': 3623, 'will': 8402, 'fulfil': 3415, 'wonderful': 8468, 'blessing': 1567, 'at': 1260, 'times': 7722, 'date': 2451, 'sunday': 7388, 'xxxmobilemovieclub': 8556, 'use': 8069, 'credit': 2334, 'click': 2077, 'wap': 8250, 'link': 4637, 'next': 5334, 'message': 4993, 'http': 3968, 'com': 2144, 'qjkgighjjgcbl': 6182, 'oh': 5499, 'watching': 8272, 'eh': 2870, 'remember': 6366, 'how': 3953, 'spell': 7127, 'his': 3864, 'name': 5244, 'yes': 8592, 'did': 2592, 'naughty': 5271, 'make': 4848, 'wet': 8350, 'fine': 3215, 'if': 4041, 'thatåõs': 7625, 'way': 8284, 'feel': 3158, 'its': 4225, 'gota': 3595, 'england': 2927, 'macedonia': 4810, 'dont': 2716, 'miss': 5052, 'goals': 3554, 'team': 7541, 'news': 5330, 'ur': 8051, 'national': 5265, '87077': 783, 'eg': 2865, 'try': 7894, 'wales': 8225, 'scotland': 6657, '4txt': 599, 'ì¼1': 8659, 'poboxox36504w45wq': 5911, 'that': 7621, 'seriously': 6743, 'going': 3563, 'ha': 3695, 'ì_': 8658, 'pay': 5734, 'first': 3232, 'when': 8362, 'da': 2416, 'stock': 7256, 'comin': 2155, 'aft': 962, 'finish': 3218, 'lunch': 4776, 'str': 7281, 'down': 2737, 'lor': 4719, 'ard': 1182, 'smth': 7007, 'ffffffffff': 3177, 'alright': 1043, 'can': 1839, 'meet': 4958, 'sooner': 7067, 'just': 4352, 'forced': 3310, 'myself': 5228, 'eat': 2835, 'slice': 6959, 'really': 6280, 'hungry': 3988, 'tho': 7676, 'sucks': 7357, 'mark': 4885, 'getting': 3511, 'worried': 8492, 'knows': 4450, 'sick': 6877, 'turn': 7917, 'pizza': 5854, 'lol': 4696, 'always': 1052, 'convincing': 2254, 'catch': 1899, 'bus': 1771, 'are': 1183, 'frying': 3403, 'an': 1079, 'egg': 2867, 'tea': 7535, 'eating': 2838, 'mom': 5110, 'left': 4566, 'over': 5627, 'dinner': 2624, 'do': 2675, 'love': 4740, 'amp': 1071, 'we': 8289, 're': 6259, 'packing': 5653, 'car': 1861, 'll': 4669, 'let': 4587, 'know': 4447, 'room': 6514, 'ahhh': 987, 'work': 8482, 'vaguely': 8092, 'what': 8355, 'does': 2687, 'wait': 8219, 'clear': 2071, 'were': 8339, 'sure': 7414, 'being': 1478, 'sarcastic': 6613, 'why': 8385, 'doesn': 2689, 'live': 4661, 'us': 8065, 'yeah': 8580, 'was': 8259, 'apologetic': 1143, 'fallen': 3112, 'out': 5609, 'she': 6795, 'actin': 904, 'spoilt': 7154, 'child': 2010, 'caught': 1903, 'till': 7719, 'but': 1778, 'doing': 2702, 'too': 7796, 'badly': 1356, 'cheers': 1986, 'tell': 7559, 'anything': 1129, 'fear': 3150, 'of': 5477, 'fainting': 3104, 'housework': 3951, 'quick': 6193, 'cuppa': 2388, 'thanks': 7613, 'subscription': 7345, 'ringtone': 6482, 'uk': 7963, 'charged': 1955, 'month': 5126, 'please': 5879, 'confirm': 2209, 'by': 1794, 'replying': 6400, 'yup': 8637, 'look': 4707, 'timings': 7726, 'msg': 5168, 'again': 970, 'xuhui': 8551, 'learn': 4556, '2nd': 461, 'her': 3830, 'lesson': 4585, '8am': 809, 'oops': 5548, 'roommate': 6516, 'done': 2714, 'see': 6695, 'letter': 4589, 'decide': 2481, 'hello': 3814, 'saturday': 6625, 'texting': 7603, 'decided': 2482, 'tomo': 7781, 'trying': 7896, 'invite': 4180, 'pls': 5887, 'ahead': 986, 'watts': 8280, 'wanted': 8247, 'weekend': 8315, 'abiola': 855, 'forget': 3316, 'need': 5291, 'crave': 2324, 'most': 5141, 'sweet': 7445, 'arabian': 1179, 'steed': 7237, 'mmmmmm': 5079, 'yummy': 8632, '07732584351': 30, 'rodger': 6504, 'burns': 1768, 'tried': 7872, 'sms': 7002, 'nokia': 5377, 'camcorder': 1833, '08000930705': 57, 'delivery': 2521, 'tomorrow': 7783, 'who': 8378, 'seeing': 6697, 'hope': 3919, 'man': 4858, 'well': 8330, 'endowed': 2917, 'am': 1054, 'lt': 4763, 'gt': 3663, 'inches': 4091, 'calls': 1828, 'messages': 4995, 'missed': 5054, 'didn': 2594, 'get': 3503, 'hep': 3829, 'immunisation': 4070, 'nigeria': 5344, 'fair': 3105, 'hopefully': 3922, 'tyler': 7946, 'could': 2289, 'maybe': 4932, 'ask': 1234, 'bit': 1544, 'stubborn': 7309, 'hospital': 3934, 'kept': 4396, 'telling': 7560, 'weak': 8290, 'sucker': 7355, 'hospitals': 3935, 'suckers': 7356, 'thinked': 7661, 'time': 7721, 'saw': 6632, 'class': 2063, 'gram': 3615, 'usually': 8081, 'runs': 6557, 'half': 3711, 'eighth': 2873, 'smarter': 6982, 'gets': 3507, 'almost': 1038, 'whole': 8379, 'second': 6682, 'fyi': 3435, 'ride': 6472, 'morning': 5137, 'crashing': 2323, 'place': 5856, 'wow': 8508, 'never': 5321, 'realized': 6278, 'embarassed': 2898, 'accomodations': 886, 'thought': 7681, 'liked': 4616, 'since': 6902, 'best': 1498, 'seemed': 6701, 'happy': 3746, 'cave': 1907, 'sorry': 7076, 'give': 3532, 'offered': 5484, 'embarassing': 2899, 'ac': 872, 'sptv': 7176, 'new': 5325, 'jersey': 4288, 'devils': 2573, 'detroit': 2567, 'red': 6320, 'wings': 8414, 'play': 5870, 'ice': 4022, 'hockey': 3886, 'correct': 2271, 'incorrect': 4102, 'end': 2913, 'mallika': 4857, 'sherawat': 6802, 'yesterday': 8594, 'find': 3212, 'url': 8061, 'congrats': 2215, 'year': 8581, 'special': 7114, 'cinema': 2049, 'pass': 5711, 'yours': 8619, '09061209465': 219, 'suprman': 7412, 'matrix3': 4918, 'starwars3': 7218, 'etc': 2986, 'bx420': 1792, 'ip4': 4189, '5we': 641, '150pm': 353, 'later': 4525, 'meeting': 4960, 'where': 8366, 'reached': 6262, 'gauti': 3469, 'sehwag': 6706, 'odi': 5476, 'series': 6741, 'pick': 5826, 'burger': 1763, 'yourself': 8620, 'move': 5154, 'pain': 5660, 'killing': 4421, 'good': 3576, 'joke': 4314, 'girls': 3529, 'situation': 6925, 'seekers': 6698, 'part': 5700, 'checking': 1980, 'iq': 4195, 'roommates': 6517, 'took': 7797, 'forever': 3313, 'come': 2150, 'double': 2730, 'check': 1976, 'hair': 3706, 'dresser': 2760, 'said': 6583, 'wun': 8536, 'cut': 2403, 'short': 6837, 'nice': 5338, 'pleased': 5880, 'advise': 945, 'following': 3291, 'recent': 6301, 'review': 6459, 'mob': 5087, 'awarded': 1320, '1500': 350, 'bonus': 1608, '09066364589': 267, 'song': 7061, 'dedicated': 2492, 'which': 8372, 'dedicate': 2491, 'valuable': 8098, 'frnds': 3389, 'rply': 6533, 'complimentary': 2184, 'trip': 7873, 'eurodisinc': 2992, 'trav': 7855, 'aco': 900, 'entry41': 2950, '1000': 299, 'dis': 2636, '18': 368, 'morefrmmob': 5134, 'shracomorsglsuplt': 6862, '10': 297, 'ls1': 4759, '3aj': 518, 'hear': 3793, 'divorce': 2665, 'barbie': 1387, 'comes': 2152, 'ken': 4394, 'plane': 5862, 'wah': 8212, 'lucky': 4770, 'save': 6628, 'money': 5117, 'hee': 3806, 'finished': 3220, 'hi': 3846, 'babe': 1342, 'im': 4058, 'wanna': 8243, 'something': 7049, 'xx': 8552, 'performed': 5771, 'waiting': 8222, 'machan': 4812, 'once': 5529, 'thats': 7624, 'cool': 2259, 'gentleman': 3494, 'dignity': 2614, 'respect': 6426, 'peoples': 5763, 'very': 8130, 'much': 5186, 'shy': 6872, 'pa': 5649, 'operate': 5555, 'after': 963, 'same': 6598, 'looking': 4711, 'job': 4303, 'ta': 7473, 'earn': 2824, 'ah': 984, 'stop': 7266, 'urgnt': 8058, 'real': 6271, 'yo': 8604, 'tickets': 7709, 'one': 5531, 'jacket': 4246, 'used': 8070, 'multis': 5195, 'started': 7213, 'requests': 6407, 'came': 1834, 'bed': 1455, 'coins': 2126, 'factory': 3094, 'gotta': 3600, 'nitros': 5362, 'ela': 2878, 'kano': 4375, 'il': 4053, 'download': 2738, 'wen': 8333, 'stand': 7201, 'close': 2084, 'another': 1106, 'night': 5346, 'spent': 7132, 'late': 4522, 'afternoon': 965, 'casualty': 1897, 'means': 4946, 'haven': 3771, 'any': 1120, 'stuff42moro': 7321, 'includes': 4095, 'sheets': 6797, 'smile': 6990, 'pleasure': 5882, 'trouble': 7880, 'pours': 5984, 'rain': 6216, 'sum1': 7379, 'hurts': 3998, 'becoz': 1453, 'someone': 7043, 'loves': 4748, 'smiling': 6994, 'service': 6746, 'representative': 6404, '0800': 53, '169': 366, '6031': 647, 'between': 1507, '10am': 307, '9pm': 835, 'guaranteed': 3666, '5000': 609, 'havent': 3772, 'planning': 5866, 'buy': 1783, 'lido': 4600, '530': 627, 'show': 6853, 'collected': 2135, 'simply': 6899, 'password': 5718, 'mix': 5070, '85069': 770, 'verify': 8126, 'usher': 8076, 'britney': 1712, 'fml': 3282, 'telugu': 7565, 'movie': 5157, 'abt': 867, 'loads': 4675, 'loans': 4677, 'wk': 8443, 'hols': 3899, 'run': 6555, 'forgot': 3321, 'hairdressers': 3708, 'appointment': 1159, 'four': 3339, 'shower': 6855, 'beforehand': 1467, 'cause': 1904, 'prob': 6078, 'ham': 3717, 'nothing': 5410, 'else': 2892, 'okay': 5505, 'price': 6054, 'long': 4703, 'legal': 4569, 'them': 7636, 'ave': 1307, 'ams': 1075, 'gone': 3572, '4the': 597, 'driving': 2769, 'test': 7589, 'yet': 8595, 'mean': 4942, 'guess': 3672, 'gave': 3470, 'boston': 1629, 'men': 4979, 'changed': 1945, 'search': 6677, 'location': 4680, 'nyc': 5451, 'cuz': 2410, 'signin': 6887, 'page': 5656, 'says': 6636, 'umma': 7970, 'life': 4603, 'vava': 8112, 'lot': 4727, 'dear': 2471, 'wishes': 8427, 'birthday': 1542, 'making': 4852, 'truly': 7889, 'memorable': 4976, 'aight': 994, 'hit': 3866, 'would': 8504, 'ip': 4188, 'address': 922, 'considering': 2227, 'computer': 2190, 'isn': 4213, 'minecraft': 5030, 'server': 6745, 'grumpy': 3660, 'old': 5517, 'people': 5762, 'better': 1504, 'lying': 4790, 'jokes': 4316, 'worry': 8494, 'busy': 1777, 'plural': 5891, 'noun': 5417, 'research': 6412, 'cos': 2276, 'things': 7659, 'scared': 6642, 'mah': 4835, 'loud': 4735, 'gent': 3492, 'contact': 2232, 'last': 4519, 'weekends': 8316, 'draw': 2752, 'shows': 6861, '09064012160': 243, 'k52': 4358, '12hrs': 333, '150ppm': 355, 'wa': 8207, 'openin': 5552, 'sentence': 6734, 'formal': 3325, 'anyway': 1132, 'juz': 4357, 'tt': 7904, 'eatin': 2837, 'puttin': 6171, 'weight': 8321, 'haha': 3702, 'anythin': 1128, 'happened': 3738, 'entered': 2939, 'cabin': 1801, 'boss': 1628, 'felt': 3167, 'askd': 1235, 'invited': 4181, 'apartment': 1137, 'went': 8336, 'specially': 7118, 'holiday': 3896, 'flights': 3258, 'inc': 4089, 'operator': 5556, '0871277810910p': 129, 'min': 5023, 'goodo': 3585, 'must': 5214, 'friday': 3376, 'potato': 5976, 'ratio': 6245, 'tortilla': 7814, 'needed': 5293, 'hmm': 3878, 'uncle': 7979, 'informed': 4125, 'paying': 5739, 'school': 6648, 'directly': 2630, 'food': 3298, 'private': 6070, '2004': 401, 'account': 889, 'statement': 7221, '07742676969': 32, '786': 709, 'unredeemed': 8023, 'points': 5921, '08719180248': 175, 'identifier': 4034, '45239': 570, 'expires': 3065, '2000': 399, 'caller': 1821, '03': 15, 'landline': 4499, '09064019788': 249, 'box42wr29c': 1655, 'apples': 1154, 'pairs': 5664, 'malarky': 4854, 'todays': 7764, 'voda': 8176, 'numbers': 5437, 'ending': 2915, '7548': 701, '350': 506, 'award': 1319, 'match': 4906, '08712300220': 111, 'quoting': 6204, '4041': 543, 'standard': 7202, 'rates': 6243, 'app': 1147, 'sao': 6607, 'mu': 5184, 'ìï': 8661, 'predict': 6016, 'buying': 1786, 'yetunde': 8597, 'hasn': 3759, 'sent': 6733, 'bother': 1632, 'sending': 6725, 'involve': 4185, 'shouldn': 6848, 'imposed': 4077, 'apologise': 1144, 'girl': 3526, 'del': 2511, 'bak': 1364, 'sum': 7378, 'lucyxx': 4773, 'tmorrow': 7749, 'accomodate': 885, 'answer': 1109, 'sunshine': 7395, 'quiz': 6200, 'top': 7805, 'sony': 7063, 'dvd': 2812, 'player': 5872, 'country': 2296, 'algarve': 1022, 'ansr': 1108, '82277': 744, 'sp': 7099, 'tyrone': 7950, 'laid': 4491, 'dogging': 2696, 'locations': 4681, 'direct': 2629, 'join': 4311, 'largest': 4516, 'bt': 1738, 'txting': 7939, 'gravel': 3628, '69888': 675, 'nt': 5427, 'ec2a': 2840, '31p': 498, 'haf': 3701, 'msn': 5175, 'yijue': 8601, 'hotmail': 3942, 'him': 3857, 'rooms': 6518, 'befor': 1465, 'activities': 910, 'msgs': 5174, 'chat': 1966, 'svc': 7430, 'hardcore': 3748, 'services': 6747, '69988': 679, 'age': 973, 'yr': 8627, 'lazy': 4542, 'type': 7947, 'lect': 4563, 'pouch': 5979, 'sir': 6914, 'mail': 4840, 'swt': 7459, 'nver': 5445, 'tired': 7729, 'little': 4660, 'lovable': 4739, 'persons': 5789, 'coz': 2309, 'somtimes': 7058, 'those': 7677, 'occupy': 5469, 'biggest': 1524, 'their': 7633, 'hearts': 3799, 'gud': 3668, 'ni8': 5336, 'open': 5549, 'ya': 8565, 'dot': 2729, 'whats': 8357, 'staff': 7193, 'taking': 7493, 'replied': 6397, 'randy': 6236, 'sexy': 6763, 'female': 3168, 'local': 4679, 'luv': 4781, 'netcollex': 5312, 'ltd': 4764, '08700621170150p': 81, 'ummma': 7972, 'begin': 1471, 'qatar': 6177, 'pray': 6011, 'hard': 3747, 'deleted': 2515, 'sindu': 6904, 'birla': 1538, 'soft': 7029, 'wine': 8412, 'flowing': 3273, 'nevering': 5322, 'thk': 7670, 'plaza': 5877, 'typical': 7949, 'everywhere': 3016, 'dirt': 2633, 'floor': 3267, 'windows': 8409, 'shirt': 6816, 'sometimes': 7051, 'mouth': 5153, 'dream': 2755, 'without': 8437, 'chores': 2037, 'joy': 4329, 'lots': 4729, 'tv': 7922, 'exist': 3050, 'hail': 3705, 'mist': 5062, 'become': 1451, 'aaooooright': 845, 'leaving': 4562, 'house': 3948, 'interview': 4167, 'boy': 1660, 'missing': 5056, 'annoncement': 1099, 'years': 8582, '07046744435': 24, 'arrange': 1210, '0871277810810': 128, 'keep': 4389, 'safe': 6578, 'because': 1449, 'envy': 2955, 'everyone': 3010, 'parents': 5693, 'hand': 3720, 'excited': 3038, 'each': 2818, 'spend': 7130, 'bootydelious': 1621, '32': 499, 'inviting': 4182, 'friend': 3380, '434': 556, 'frnd': 3388, '62468': 655, 'bangbabes': 1378, 'order': 5578, 'should': 6846, 'content': 2236, 'goto': 3599, 'bangb': 1377, 'internet': 4166, 'menu': 4986, 'cultures': 2382, 'module': 5103, '09061701939': 226, 's89': 6568, 'avoid': 1313, 'missunderstding': 5060, 'wit': 8432, 'beloved': 1488, 'escape': 2976, 'fancy': 3123, 'bridge': 1697, 'needs': 5296, 'lager': 4490, 'completely': 2180, 'form': 3324, 'clark': 2060, 'also': 1045, 'utter': 8083, 'waste': 8264, 'axis': 1328, 'bank': 1380, 'hmmm': 3879, 'hop': 3918, 'muz': 5220, 'discuss': 2649, 'liao': 4594, 'coming': 2156, 'bloody': 1581, 'hell': 3812, 'cant': 1851, 'believe': 1479, 'surname': 7420, 'mr': 5163, 'ill': 4055, 'clue': 2100, 'spanish': 7106, 'begins': 1472, 'bath': 1411, 'carlos': 1878, 'mall': 4856, 'turns': 7920, 'staying': 7228, 'til': 7718, 'smoke': 6996, 'worth': 8498, 'doesnt': 2690, 'log': 4687, 'spoke': 7155, 'maneesha': 4868, 'satisfied': 6622, 'experience': 3060, 'toll': 7777, 'lifted': 4609, 'hopes': 3924, 'offer': 5483, 'especially': 2980, 'approaches': 1163, 'studying': 7318, 'anyways': 1133, 'gr8': 3608, 'trust': 7891, 'guys': 3688, 'bye': 1796, 'handsome': 3726, 'finding': 3213, 'working': 8486, 'towards': 7828, 'mummy': 5199, 'boytoy': 1665, 'awesome': 1322, 'minute': 5041, 'freephone': 3366, '0808': 65, '145': 343, '4742': 574, '9am': 833, '11pm': 321, 'xmas': 8548, 'radio': 6209, 'jus': 4351, 'bathe': 1412, 'sis': 6916, 'using': 8077, 'finishes': 3221, 'unique': 8008, '30th': 494, 'august': 1289, 'areyouunique': 1189, 'joined': 4312, 'league': 4554, 'touch': 7823, 'deal': 2467, 'personal': 5786, 'finally': 3209, 'completed': 2179, 'course': 2302, 'itself': 4226, 'however': 3957, 'suggest': 7370, 'stays': 7229, 'able': 857, 'ors': 5591, 'every': 3005, 'stool': 7265, 'settled': 6754, 'wishin': 8428, 'mrng': 5165, 'hav': 3768, 'story': 7280, 'hamster': 3719, 'dead': 2466, 'tmr': 7750, '1pm': 385, 'orchard': 5577, 'mrt': 5166, 'kate': 4380, 'evening': 2999, 'babyjontet': 1347, 'found': 3338, 'enc': 2912, 'bucks': 1742, 'darlin': 2442, 'ive': 4232, 'college': 2139, 'refilled': 6330, 'successfully': 7353, 'inr': 4140, 'decimal': 2484, 'keralacircle': 4398, 'prepaid': 6027, 'balance': 1367, 'rs': 6535, 'transaction': 7845, 'id': 4028, 'kr': 4464, 'goodmorning': 3581, 'sleeping': 6953, 'ga': 3438, 'alter': 1046, 'dat': 2449, 'ericsson': 2963, 'oso': 5596, 'cannot': 1850, 'oredi': 5581, 'dats': 2455, 'straight': 7283, 'dogg': 2694, 'connection': 2220, 'before': 1466, 'refund': 6335, 'bill': 1526, 'both': 1631, 'shoot': 6831, 'big': 1522, 'ready': 6270, 'bruv': 1733, 'break': 1682, 'rewarding': 6462, 'semester': 6719, 'study': 7317, 'noe': 5371, 'leh': 4572, 'sounds': 7088, 'heading': 3785, 'prediction': 6019, 'slept': 6958, 'past': 5720, 'few': 3174, 'nights': 5349, 'easy': 2834, 'sen': 6722, 'exam': 3033, 'march': 4880, 'atm': 1267, 'register': 6343, 'os': 5594, 'called': 1820, 'ubandu': 7953, 'installing': 4149, 'disk': 2652, 'important': 4075, 'files': 3197, 'system': 7469, 'repair': 6389, 'shop': 6832, 'happen': 3736, 'romantic': 6511, 'nite': 5360, 'scenery': 6645, '500': 608, '89545': 805, 'collect': 2134, 'tc': 7531, 'biz': 1550, '2optout': 465, '087187262701': 161, '50gbp': 613, 'mtmsg18': 5181, 'appreciate': 1161, 'partner': 5705, 'career': 1869, 'off': 5479, 'flyng': 3280, 'start': 7212, 'horo': 3930, 'followed': 3289, 'star': 7206, 'sign': 6883, 'aries': 1196, 'company': 2168, 'elama': 2882, 'po': 5897, 'mudyadhu': 5189, 'strict': 7295, 'than': 7609, 'teacher': 7537, 'bcoz': 1433, 'teaches': 7539, 'conducts': 2204, 'lessons': 4586, 'gandhipuram': 3452, 'walk': 8227, 'cross': 2348, 'road': 6494, 'side': 6879, 'street': 7288, 'rubber': 6543, 'battery': 1417, 'died': 2599, 'flirt': 3262, '10p': 309, 'sam': 6594, '25': 422, 'recd': 6294, 'thirtyeight': 7667, 'pence': 5757, 'printed': 6063, 'upstairs': 8048, 'closer': 2087, 'wil': 8398, 'reach': 6260, 'theory': 7643, 'argument': 1194, 'wins': 8419, 'loses': 4723, 'person': 5784, 'argue': 1192, 'kick': 4410, '447801259231': 562, 'secret': 6685, 'admirer': 929, 'reveal': 6455, 'thinks': 7664, '09058094597': 209, 'tomarrow': 7779, 'hearing': 3796, 'laptop': 4511, 'case': 1888, 'pleassssssseeeeee': 5881, 'tel': 7554, 'avent': 1309, 'sportsx': 7165, 'shining': 6811, 'meant': 4947, 'signing': 6888, 'although': 1048, 'told': 7774, 'into': 4171, 'baig': 1361, 'face': 3090, 'watches': 8270, 'watch': 8268, 'fr': 3345, 'thanx': 7618, 'everythin

In [ ]:
from sklearn.preprocessing import LabelEncoder     #using label encoder to covert catagorical data into numerical
le=LabelEncoder()
df['v1']=le.fit_transform(df['v1'])     #covert v1 column into numerical

In [ ]:
le.classes_ # how many classes are exist in v1

array(['ham', 'spam'], dtype=object)

In [ ]:
#take v1 as a output variable
y=df['v1'].values
y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split     #split the dataset into 80 ,20 ratio for training and testing
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#import naive base model
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(xtrain,ytrain)

MultinomialNB()

In [ ]:
ypred=model.predict(xtest)   #predict the y using testing data

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
accuracy_score(ytest,ypred)

[[939  10]
 [  9 157]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       949
           1       0.94      0.95      0.94       166

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115

0.9829596412556054

For 80% ,20% training testing data prdiction has a nominal error ,and the accuracy score is 98%